// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4SpaGAEIXvteqba4ieiBgiV4wM_8I5KE',
    appId: '1:301858564949:web:03a86d08df306bc41c5ddc',
    messagingSenderId: '301858564949',
    projectId: 'it-world-64669',
    authDomain: 'it-world-64669.firebaseapp.com',
    storageBucket: 'it-world-64669.appspot.com',
    measurementId: 'G-XVCRQ8HVLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8PPNbR3LL9eIqsINRUj_SSXtdC-icmR8',
    appId: '1:301858564949:android:97628853df72bd191c5ddc',
    messagingSenderId: '301858564949',
    projectId: 'it-world-64669',
    storageBucket: 'it-world-64669.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZTFfteRNoihycxcUOzgLS-UhZN4KlTAg',
    appId: '1:301858564949:ios:ec87599d53a90e361c5ddc',
    messagingSenderId: '301858564949',
    projectId: 'it-world-64669',
    storageBucket: 'it-world-64669.appspot.com',
    iosClientId: '301858564949-8h488mce9lto1ho54rgbt0fp0us16q4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.itWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZTFfteRNoihycxcUOzgLS-UhZN4KlTAg',
    appId: '1:301858564949:ios:9b475552b6f6dd721c5ddc',
    messagingSenderId: '301858564949',
    projectId: 'it-world-64669',
    storageBucket: 'it-world-64669.appspot.com',
    iosClientId: '301858564949-heejtbcv670c1o0utkgecbmsr1ss6qdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.itWorld.RunnerTests',
  );
}
